# Generated by Django 2.2.13 on 2022-02-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidades', models.CharField(default='Some String', max_length=100, verbose_name='Entidades')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(default='Some String', max_length=100, verbose_name='Municipio')),
                ('entidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidades')),
            ],
        ),
    ]
