# Generated by Django 2.2.13 on 2022-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesCabildo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200, verbose_name='Entidad')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
                ('ayuntamiento', models.CharField(max_length=12, verbose_name='Ayuntamiento')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('tipo_de_sesion', models.CharField(choices=[('1', 'Solemne'), ('2', 'Ordinaria'), ('3', 'Extraordinaria')], max_length=1, verbose_name='Tipo de sesión')),
                ('modalidad', models.CharField(choices=[('1', 'Presencial'), ('2', 'Virtual')], max_length=1, verbose_name='Modalidad')),
                ('actas', models.ImageField(blank=True, upload_to='pdf', verbose_name='actas')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_to', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
