# Generated by Django 2.2.13 on 2022-02-01 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabildo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Entidad',
            },
        ),
        migrations.RemoveField(
            model_name='sesionescabildo',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='sesionescabildo',
            name='municipio',
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabildo.Entidades')),
            ],
            options={
                'verbose_name': 'Municipio',
            },
        ),
        migrations.AddField(
            model_name='sesionescabildo',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabildo.Municipio'),
        ),
    ]
