# Generated by Django 2.2.13 on 2022-02-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabildo', '0002_auto_20220201_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='sesionescabildo',
            name='lugar',
        ),
        migrations.DeleteModel(
            name='Entidades',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
