# Generated by Django 2.2.13 on 2022-07-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_comentariospost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comentariospost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='comentarios',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='comentariospost',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='preguntas.Comentarios'),
        ),
    ]
