# Generated by Django 2.2.13 on 2022-03-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normatividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_let', models.CharField(choices=[('1', 'Ley general'), ('2', 'Reglamento municipal'), ('3', 'Ley local'), ('4', 'Reglamento municipal')], max_length=1, verbose_name='Tipo de sesión')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fuentes', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/', verbose_name='fuentes')),
                ('fecha_de_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('ultima_reforma', models.DateTimeField(blank=True, null=True, verbose_name='Ultima reforma')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_to', models.DateTimeField(auto_now_add=True, null=True)),
                ('entidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidades')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Municipio')),
            ],
        ),
    ]
