# Generated by Django 2.2.13 on 2022-02-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normatividad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SesionesCabildo',
            new_name='Normatividad',
        ),
    ]
