# Generated by Django 2.2.13 on 2022-04-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normatividad', '0002_auto_20220322_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Some String', max_length=100, verbose_name='tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='normatividad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normatividad.Tipo', verbose_name='Tipo'),
        ),
    ]
