# Generated by Django 2.2.13 on 2022-03-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_1', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_1_presidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_1_presidencia', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_1_secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_1_secretaria', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_2', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_2_presidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_2_presidencia', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_2_secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_2_secretaria', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_3', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_3_secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_3_secretaria', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_4', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_4_secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_4_secretaria', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_5', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_6', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_7', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_8', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comision_9', models.CharField(default='Some String', max_length=100, verbose_name='comision')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(default='Some String', max_length=100, verbose_name='partido')),
            ],
        ),
        migrations.CreateModel(
            name='Regidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayuntamiento', models.CharField(max_length=12, verbose_name='Ayuntamiento')),
                ('cargo', models.CharField(choices=[('1', 'Presidente Muncipal'), ('2', 'Suplente Presidente'), ('3', 'Síndico Procurador'), ('4', 'Suplente Síndico'), ('5', 'Regidor MR'), ('6', 'Regidor RP')], max_length=2, verbose_name='Cargo')),
                ('genero', models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino'), ('3', 'No binario')], default=1, max_length=1, verbose_name='Genero')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('nombre_suplente', models.CharField(default='Some String', max_length=300, verbose_name='Nombre del suplente')),
                ('apellido_paterno_suplente', models.CharField(default='Some String', max_length=100, verbose_name='Apellido paterno del suplente')),
                ('apellido_materno_suplente', models.CharField(default='Some String', max_length=120, verbose_name='Apellido materno del suplente')),
                ('foto', models.ImageField(blank=True, upload_to='img', verbose_name='Foto')),
                ('telefono', models.IntegerField(max_length=10, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=120, verbose_name='Correo')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('status', models.CharField(choices=[('1', 'Borrador'), ('2', 'Publicado'), ('3', 'Finalizado')], default=1, max_length=1)),
                ('actas', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/', verbose_name='actas')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_to', models.DateTimeField(auto_now_add=True, null=True)),
                ('comision_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_1')),
                ('comision_1_presidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_1_presidencia')),
                ('comision_1_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_1_secretaria')),
                ('comision_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_2')),
                ('comision_2_presidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_2_presidencia')),
                ('comision_2_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_2_secretaria')),
                ('comision_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_3')),
                ('comision_3_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_3_secretaria')),
                ('comision_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_4')),
                ('comision_4_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_4_secretaria')),
                ('comision_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_5')),
                ('comision_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_6')),
                ('comision_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_7')),
                ('comision_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_8')),
                ('comision_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Comision_9')),
                ('entidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidades')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Municipio')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regidurias.Partido')),
            ],
        ),
    ]
