# Generated by Django 2.2.13 on 2022-03-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('regidurias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regidores',
            new_name='Regidurias',
        ),
    ]
