# Generated by Django 2.2.13 on 2022-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regidurias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regidores',
            name='cargo_secundario',
        ),
        migrations.AddField(
            model_name='regidores',
            name='apellido_materno_suplente',
            field=models.CharField(default='Some String', max_length=120, verbose_name='Apellido materno del suplente'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='apellido_paterno_suplente',
            field=models.CharField(default='Some String', max_length=100, verbose_name='Apellido paterno del suplente'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_1_presidencia',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 1 presidencia'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_1_secretaria',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 1 secretaria'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_2_presidencia',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 2 presidencia'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_2_secretaria',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 2 secretaria'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_3_secretaria',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 3 secretaria'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='comision_4_secretaria',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 4 secretaria'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='genero',
            field=models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino')], default=1, max_length=1, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='regidores',
            name='nombre_suplente',
            field=models.CharField(default='Some String', max_length=300, verbose_name='Nombre del suplente'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='cargo',
            field=models.CharField(choices=[('1', 'Presidente Muncipal'), ('2', 'Suplente Presidente'), ('3', 'Síndico Procurador'), ('4', 'Suplente Síndico'), ('5', 'Regidor MR'), ('6', 'Regidor RP')], max_length=2, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_1',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 1'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_2',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 2'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_3',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 3'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_4',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 4'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_5',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 5'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_6',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 6'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_7',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 7'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_8',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 8'),
        ),
        migrations.AlterField(
            model_name='regidores',
            name='comision_9',
            field=models.CharField(choices=[('1', 'Gobernación, Legislación y Mejora Regulatoria'), ('2', 'Hacienda y Patrimonio Municipal'), ('3', 'Transparencia, Rendición de Cuentas y Combate a la Corrupción'), ('4', 'Seguridad Ciudadana y Protección Civil'), ('5', 'Planeación, Urbanismo, Obras y Servicios Públicos'), ('6', 'Medio Ambiente, Desarrollo Sustentable y Salud'), ('7', 'Vialidad y Movilidad Urbana'), ('8', 'Desarrollo Metropolitano'), ('9', 'Educación, Cultura, Bibliotecas, Ciencia y Tecnología'), ('10', 'Juventud y Deporte'), ('11', 'Bienestar Social'), ('12', 'Desarrollo Económico, Turismo y Asuntos Fronterizos'), ('13', 'Recreación, Espectáculos y Alcoholes'), ('14', 'Igualdad de Género'), ('15', 'Derechos Humanos, Migración y Asuntos Indígenas'), ('16', 'Participación Ciudadana'), ('17', 'Régimen Interno'), ('18', 'Planeación, Urbanismo, Desarrollo Metropolitano, Obras y Servicios Públicos'), ('19', 'Coordinación Política')], default=1, max_length=2, verbose_name='Comisión 9'),
        ),
    ]
