# Generated by Django 2.2.13 on 2022-01-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regidurias', '0002_auto_20220120_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidores',
            name='status',
            field=models.CharField(choices=[('1', 'Borrador'), ('2', 'Publicado'), ('3', 'Finalizado')], default=1, max_length=1),
        ),
    ]
