# Generated by Django 2.2.13 on 2022-02-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regidurias', '0003_regidores_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regidores',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='regidores',
            name='municipio',
        ),
    ]
