# Generated by Django 2.2.13 on 2022-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regidurias', '0003_auto_20220421_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidurias',
            name='slug',
            field=models.CharField(default='poner el nombre del regidor', max_length=100, verbose_name='slug'),
        ),
    ]
