# Generated by Django 2.2.13 on 2022-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regidurias', '0005_auto_20220426_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='regidurias',
            name='actas_dos',
            field=models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/', verbose_name='actas 2'),
        ),
        migrations.AlterField(
            model_name='regidurias',
            name='facebook',
            field=models.CharField(blank=True, default='Some String', max_length=320, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='regidurias',
            name='genero',
            field=models.CharField(choices=[('1', 'Mujer'), ('2', 'Hombre'), ('3', 'No binario')], default=1, max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='regidurias',
            name='instagram',
            field=models.CharField(blank=True, default='Some String', max_length=320, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='regidurias',
            name='twitter',
            field=models.CharField(blank=True, default='Some String', max_length=320, null=True, verbose_name='Twitter'),
        ),
    ]
