# Generated by Django 2.2.13 on 2022-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200, verbose_name='Entidad')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
                ('year', models.IntegerField(max_length=4, verbose_name='Año')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('presupuesto_per_capital', models.FloatField(verbose_name='Presupuesto pre capital')),
                ('servicos_personales', models.FloatField(verbose_name='Servicios personales')),
                ('comunicacion_social', models.FloatField(verbose_name='Comunicación social')),
                ('gasto_social', models.FloatField(verbose_name='Gasto social')),
                ('fuentes', models.ImageField(blank=True, upload_to='pdf', verbose_name='fuentes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_to', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
