# Generated by Django 2.2.13 on 2022-03-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, verbose_name='Año')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('presupuesto_per_capital', models.FloatField(verbose_name='Presupuesto pre capital')),
                ('servicos_personales', models.FloatField(verbose_name='Servicios personales')),
                ('comunicacion_social', models.FloatField(verbose_name='Comunicación social')),
                ('gasto_social', models.FloatField(verbose_name='Gasto social')),
                ('fuentes', models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/', verbose_name='fuentes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_to', models.DateTimeField(auto_now_add=True, null=True)),
                ('entidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidades')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Municipio')),
            ],
        ),
    ]
