# Generated by Django 2.2.13 on 2022-03-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuesto_per_capital',
            field=models.FloatField(verbose_name='Presupuesto per capital'),
        ),
    ]
