# Generated by Django 2.2.13 on 2022-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_auto_20220322_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
