# Generated by Django 2.2.13 on 2022-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_auto_20220421_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fuentes_dos',
            field=models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/', verbose_name='fuentes2'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuesto_per_capital',
            field=models.FloatField(verbose_name='Presupuesto per cápita'),
        ),
    ]
