# Generated by Django 2.2.13 on 2022-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_noticias_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
