# Generated by Django 2.2.13 on 2022-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220426_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='noticias',
            field=models.TextField(blank=True, default='Some String', max_length=3000, null=True, verbose_name='noticia'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.TextField(default='Some String', verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='noticias_link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='noticias_link'),
        ),
    ]
