# Generated by Django 2.2.13 on 2022-04-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220427_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='noticias_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='noticias',
            new_name='nota',
        ),
    ]
