# Generated by Django 2.2.13 on 2022-05-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220427_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.CharField(blank=True, default='aquí no poner nada', max_length=1000, null=True, unique=True),
        ),
    ]
