# Generated by Django 2.2.13 on 2022-05-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_acercadenosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='acercadenosotros',
            name='imagen0',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
